- name: Install Node.js and npm
  apt:
    name:
      - nodejs
      - npm
    state: present
  tags: install

- name: Install PM2
  npm:
    path: /opt/userapi 
    name: pm2
    global: yes 
    state: present
  become: true