apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus
  namespace: prometheus
spec:
  selector: 
    matchLabels:
      app: prometheus
  template:
    metadata:
      labels: 
        app: prometheus
    spec:
      containers:
      - name: prometheus
        image: prom/prometheus
        volumeMounts:
        - name: prometheus-config
          mountPath: /etc/prometheus/
        resources:
          limits:
            cpu: 200m
            memory: 512Mi
          requests:
            cpu: 100m
            memory: 256Mi
      volumes:
      - name: prometheus-config
        configMap:
          name: prometheus-config
