apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: prometheus 
data:
  prometheus.yml: |
    global:
     scrape_interval:     15s
     evaluation_interval: 15s
      scrape_configs:
        - job_name: 'userapi'
          kubernetes_sd_configs:
            - role: service
              namespaces:
                - prometheus
          relabel_configs:
            - sourceLabels: [__meta_kubernetes_service_name]
            targetLabel: job
            - sourceLabels: [__address__]
            targetLabel: instance
            - sourceLabels: [__meta_kubernetes_namespace]
              targetLabel: namespace
            - targetLabel: __address__
              replacement: $(instance):3000 
   

