apiVersion: apps/v1
kind: Deployment
metadata:
  name: userapi-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-api
  template:
    metadata:
      labels:
        app: user-api
    spec:
      containers:
      - name: userapi
        image: lizadan/userapi:latest
        ports:
        - containerPort: 3000
        env:
          - name: REDIS_HOST
            value: redis-service
          - name: REDIS_PORT
            value: "6379"
        volumeMounts:
        - name: userapi-data
          mountPath: /userapi/data
        resources:
          limits:
            cpu: 500m 
            memory: 1024Mi 
          requests:
            cpu: 250m 
            memory: 512Mi 
      volumes:
      - name: userapi-data
        persistentVolumeClaim:
          claimName: userapi-pvc

