Vagrant.configure("2") do |config|
  if Vagrant.has_plugin?("vagrant-vbguest")
    config.vm.provider :virtualbox do |vb|
      config.vbguest.auto_update = false
    end
  end

  config.vm.define "app_server" do |server|
    server.vm.box = "bento/ubuntu-22.04"
    server.vm.hostname = "app-server"

    server.vm.provider "virtualbox" do |vb|
      vb.name = "app-server"
      vb.memory = "2048"
      vb.cpus = 1
    end

    server.vm.provider "vmware_desktop" do |vmware|
      vmware.vmx["memsize"] = "2048"
      vmware.vmx["numvcpus"] = "1"
    end

    server.vm.network "forwarded_port", guest: 80, host: 3001, protocol: "tcp" 
    config.vm.synced_folder "../userapi", "/vagrant/userapi"
    config.vm.synced_folder "./playbooks", "/vagrant/playbooks"
 
   
  end

  config.vm.provision "ansible_local" do |ansible|
    ansible.playbook = "playbooks/run.yml"
    # ansible.verbose = true
  end
end
